export default [
  {key: 'left-spacer'},
  {
    title: 'title',
    time: 'time',
    image: 'image',
    saved: true,
    color: 'red',
    activeDot: true,
  },
  {
    title: 'title',
    time: 'time',
    image: 'image',
    saved: true,
    color: 'green',
    activeDot: false,
  },
  {
    title: 'title',
    time: 'time',
    image: 'image',
    saved: true,
    color: 'blue',
    activeDot: false,
  },
  {
    title: 'title',
    time: 'time',
    image: 'image',
    saved: true,
    color: 'blue',
    activeDot: false,
  },
  {
    title: 'title',
    time: 'time',
    image: 'image',
    saved: true,
    color: 'blue',
    activeDot: false,
  },
  {key: 'right-spacer'},
];
